### ISSUE TITLE
[2015-06-13 12:20:03] [PANIC:tokenizer.go:36] Error opening file ./data//en/tokenizer.dat panic: Error opening file ./data//en/tokenizer.dat

### ISSUE THREAD

**Issue by andyb** [advancedlogic/go-freeling#3]
All complied ok on Mac OSX once I got MITIE installed. 

Ran ./gofreeling and hit a panic - output below. Any help appreciated.

```
Go - Freeling - Natural Language Processing for Golang
This is a partial port of Freeling 3.1
Init Natural Language Processing Engine
[2015-06-13 12:20:03] [PANIC:tokenizer.go:36] Error opening file ./data//en/tokenizer.dat
panic: Error opening file ./data//en/tokenizer.dat

goroutine 1 [running]:
github.com/kdar/factorlog.(*FactorLog).Panic(0xc20810eea0, 0xc208079d50, 0x1, 0x1)
    /Users/andybritcliffe/go/src/github.com/kdar/factorlog/factorlog.go:405 +0xc8
github.com/advancedlogic/go-freeling/nlp.NewTokenizer(0xc20811abc0, 0x18, 0x44edb20)
    /Users/andybritcliffe/go/src/github.com/advancedlogic/go-freeling/nlp/tokenizer.go:36 +0x82a
github.com/advancedlogic/go-freeling/nlp.NewNLPEngine(0xc2080d56b0, 0xc2080328f0)
    /Users/andybritcliffe/go/src/github.com/advancedlogic/go-freeling/nlp/nlp.go:80 +0x13d
github.com/advancedlogic/go-freeling/engine.(*Engine).InitNLP(0xc20811ab20)
    /Users/andybritcliffe/go/src/github.com/advancedlogic/go-freeling/engine/engine.go:65 +0x752
main.main()
    /Users/andybritcliffe/go/src/github.com/advancedlogic/go-freeling/gofreeling.go:26 +0x4b

goroutine 6 [runnable]:
github.com/cheggaaa/pb.(*ProgressBar).writer(0xc208062f00)
    /Users/andybritcliffe/go/src/github.com/cheggaaa/pb/pb.go:348
created by github.com/cheggaaa/pb.(*ProgressBar).Start
    /Users/andybritcliffe/go/src/github.com/cheggaaa/pb/pb.go:104 +0xb6
```

**Comment by advancedlogic** [comment]
did you download the data.zip and unzipped it into go-freeling folder?

**Comment by andyb** [comment]
:+1: thanks that's what I was missing
